---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Atophite.
--- DateTime: 04/10/2022 19:23
---
---

local Commands = {};
Commands.Atos = {};

local zones = {};

local AtosShared = AtosDangerZones.Shared
local AtosServer = AtosDangerZones.Server

Commands.Atos.RequestAllZones = function(player, args)
    print("Player is requesting zones")
    AtosServer:sendCors(player)
end

function AtosServer:sendCors(player)
    if not zones then
        zones = AtosShared.readZonesFile()
    end
    print("sending server command to " .. player:getUsername())
    sendServerCommand(player, "Atos", "GetAllZones", {
        zones = zones
    });
end


local function onServerStarted()
    zones = AtosShared:readZonesFile()
end

local onClientCommand = function(module, command, player, args)
    if Commands[module] and Commands[module][command] then
        Commands[module][command](player, args);
    end
end

Events.OnClientCommand.Add(onClientCommand);
Events.OnServerStarted.Add(onServerStarted)