---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Atophite.
--- DateTime: 04/10/2022 19:23
---
---

local Commands = {};
Commands.Atos = {};

local ATOS_zones = {};

Commands.Atos.RequestAllZones = function(player, args)
    print("Player is requesting zones")
   ATOS_sendCors(player)
end

function ATOS_sendCors(player)
    if not ATOS_zones then
        ATOS_zones = ATOS_readZonesFile()
    end
    print("sending server command to " .. player:getUsername())
    sendServerCommand(player, "Atos", "GetAllZones", {
        zones = ATOS_zones
    });
end


local function onServerStarted()
    ATOS_zones = ATOS_readZonesFile()
end

local onClientCommand = function(module, command, player, args)
    if Commands[module] and Commands[module][command] then
        Commands[module][command](player, args);
    end
end

Events.OnClientCommand.Add(onClientCommand);
Events.OnServerStarted.Add(onServerStarted)