---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Atophite.
--- DateTime: 29/07/2023 15:31
---
local AtosConstants = AtosRadiatedZones.Constants

local function doMenu(player, context, items)
    for i, v in ipairs(items) do
        local item = v;
        if not instanceof(v, "InventoryItem") then
            item = v.items[1];
        end

        if item:getType() then
            if item:getType() == "GeigerTeller" then
                if item:getUsedDelta() > 0 then
                    context:addOption(getText("ContextMenu_measure_radiation"), item, measureRadiation, player);
                    context:addOption(getText("ContextMenu_check_geiger"), item, lookAtGeiger, player);
                end
            elseif item:getType() == "Hat_GasMask" then
                context:addOption(getText("ContextMenu_check_gasmask_filter"), item, checkGasMaskFilter, player);
            end
        end
    end
end

function takeIodinePill(item, player)
    local playerObj = getSpecificPlayer(player);
    ISTimedActionQueue.add(AtosTakeIodinePill:new(playerObj, item))
end

function measureRadiation(item, player)
    local playerObj = getSpecificPlayer(player);
    ISTimedActionQueue.add(AtosIsMeasureRadiationAction:new(playerObj, item))
end

function lookAtGeiger(item, player)
    local playerObj = getSpecificPlayer(player);
    ISTimedActionQueue.add(AtosIsCheckGeigerAction:new(playerObj, item))
end

function checkGasMaskFilter(item, player)
    local playerObj = getSpecificPlayer(player);

    local condition = item:getCondition()

    if condition <= 0 then
        playerObj:Say(getText("ContextMenu_filter_quality_empty"))
    elseif condition < 3 then
        playerObj:Say(getText("ContextMenu_filter_quality_bad"))
    elseif condition < 6 then
        playerObj:Say(getText("ContextMenu_filter_quality_medium"))
    elseif condition >= 6 then
        playerObj:Say(getText("ContextMenu_filter_quality_good"))

    end

end


-------------------------- OVERRIDE--------------------------------------
ISInventoryPaneContextMenu.wearItem = function(item, player)
    -- if clothing isn't in main inventory, put it there first.
    local playerObj = getSpecificPlayer(player);
    -- This stuff was removed in that it forced the first optional clothing option when trying to wear clothing items with multiple options.
    -- It seems to work fine as intended without it.
    -- wear the clothe
    -- if item:getClothingItemExtraOption() and item:getClothingItemExtra() and item:getClothingItemExtra():get(0) then
    -- ISInventoryPaneContextMenu.onClothingItemExtra(item, item:getClothingItemExtra():get(0), playerObj);
    -- else
    ISInventoryPaneContextMenu.transferIfNeeded(playerObj, item);

    local clothingTypeByMap = AtosConstants.protectionTypeMap[clothingItemType]

    if clothingTypeByMap == "HazmatSuit" then
        ISTimedActionQueue.add(ISWearClothing:new(playerObj, item, 750));
    else
        ISTimedActionQueue.add(ISWearClothing:new(playerObj, item, 50));
    end
    -- end

end

-------------------------- OVERRIDE------------------------------------------
ISInventoryPaneContextMenu.unequipItem = function(item, player)
    if not getSpecificPlayer(player):isEquipped(item) then return end
    if item ~= nil and item:getType() == "CandleLit" then item = ISInventoryPaneContextMenu.litCandleExtinguish(item, player) end

    local clothingTypeByMap = AtosConstants.protectionTypeMap[clothingItemType]

    if clothingTypeByMap == "HazmatSuit" then
        ISTimedActionQueue.add(ISUnequipAction:new(getSpecificPlayer(player), item, 500));
    else
        ISTimedActionQueue.add(ISUnequipAction:new(getSpecificPlayer(player), item, 50));
    end
end

-- The link to the right-click menu event
Events.OnFillInventoryObjectContextMenu.Add(doMenu);
