---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Wesley.
--- DateTime: 09/10/2022 21:14
---
local AtosClient = AtosRadiatedZones.Client


function OnEat_Iodine(food, player, percentage)

    if player == getPlayer() then

        --print(player:getUsername() + "Taking iodine")
        AtosClient:setIsProtectedByPills(true)
        AtosClient:setIsProtectedByPillsSince(GameTime:getInstance():getWorldAgeHours())
        AtosClient:setIodineMoodle(1.0)
        local rad = AtosClient:getRadiation()
        local minusRad = 25

        if rad <= 25 then
            AtosClient:setRadiation(1)
        else
            AtosClient:setRadiation(rad - 25)
        end
    end

end