---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Atophite.
--- DateTime: 09/10/2022 21:14
---
local AtosClient = AtosRadiatedZones.Client


function OnEat_Iodine(food, player, percentage)

    local rad = AtosClient:getRadiation()
    local radHeal = 100
    local currentWorldHour = GameTime:getInstance():getWorldAgeHours()
    local isProtectedByPillsHours = currentWorldHour - AtosClient:getIsProtectedByPillsSince()

    AtosClient:setIsProtectedByPillsSince(GameTime:getInstance():getWorldAgeHours())

    if isProtectedByPillsHours >= 12  then


        -- Pills cannot be spammed and player needs to wait 12 hours before player can take a new pill
        if rad <= radHeal then
            AtosClient:setRadiation(1)
        else
            AtosClient:setRadiation(rad - radHeal)
        end
    end

    AtosClient:setIsProtectedByPills(true)
    AtosClient:setIodineMoodle(1.0)
end

function OnEat_LuckySoda(food, player, percentage)
    if percentage == 1 then
        print("player drank fully lucky soda")
        AtosClient:setHasLuckySodaUsage(true)
    end

end


---- OVERRIDE----------------------------------------------------------------------------------
----- OnEat_Cigarettes IS NOT RECIPE CODE.  IT IS CALLED BY IsoGameCharacter.Eat() -----
-- smoking cigarettes gives more bonus to a smoker
function OnEat_Cigarettes(food, character, percent)
    local script = food:getScriptItem()
    percent = percent * (food:getStressChange() * 100) / script:getStressChange()
    local bodyDamage = character:getBodyDamage()
    local stats = character:getStats()

    if character:HasTrait("Smoker") then
        bodyDamage:setUnhappynessLevel(bodyDamage:getUnhappynessLevel() - 10 * percent);
        if bodyDamage:getUnhappynessLevel() < 0 then
            bodyDamage:setUnhappynessLevel(0);
        end
        stats:setStress(stats:getStress() - 10 * percent);
        if stats:getStress() < 0 then
            stats:setStress(0);
        end
        local reduceSFC = stats:getMaxStressFromCigarettes()
        stats:setStressFromCigarettes(stats:getStressFromCigarettes() - reduceSFC * percent);
        character:setTimeSinceLastSmoke(stats:getStressFromCigarettes() / stats:getMaxStressFromCigarettes());
    else
        --        bodyDamage:setUnhappynessLevel(bodyDamage:getUnhappynessLevel() + 5);
        --        if bodyDamage:getUnhappynessLevel() > 100 then
        --            bodyDamage:setUnhappynessLevel(100);
        --        end
        bodyDamage:setFoodSicknessLevel(bodyDamage:getFoodSicknessLevel() + 14 * percent);
        if bodyDamage:getFoodSicknessLevel() > 100 then
            bodyDamage:setFoodSicknessLevel(100);
        end
    end

    local getCurrentRadiation = AtosClient:getRadiation()
    local radiationReductionFromSmoking = 2.0
    local newRadiationValue = (getCurrentRadiation - radiationReductionFromSmoking)

    AtosClient:setRadiation(newRadiationValue) -- smoking removes 2 radiation

end