---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Wesley.
--- DateTime: 09/10/2022 21:14
---
local AtosClient = AtosRadiatedZones.Client


function OnEat_Iodine(food, player, percentage)

    local rad = AtosClient:getRadiation()
    local radHeal = 50
    local currentWorldHour = GameTime:getInstance():getWorldAgeHours()
    local isProtectedByPillsHours = currentWorldHour - AtosClient:getIsProtectedByPillsSince()

    AtosClient:setIsProtectedByPillsSince(GameTime:getInstance():getWorldAgeHours())

    if isProtectedByPillsHours >= 12  then

        -- I change the protectedbyPillsSince so the player doesn't get punished if player takes it too early.
        -- Pills cannot be spammed and player needs to wait 14 hours before player can take a new pill
        if rad <= radHeal then
            AtosClient:setRadiation(1)
        else
            AtosClient:setRadiation(rad - radHeal)
        end
    end

    AtosClient:setIsProtectedByPills(true)
    AtosClient:setIodineMoodle(1.0)
end