---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Atophite.
--- DateTime: 04/10/2022 19:23
---
---

if isServer() and not isClient() then
   return
end

local AtosClient = AtosRadiatedZones.Client

function AtosClient:printCors()

   for playerIndex = 0, getNumActivePlayers() -1 do
      local player = getSpecificPlayer(playerIndex)
      print(player:getUsername() .. " X: " .. player:getLx() .. " Y: " .. player:getLy() .. " Z: " .. player:getLz())
   end
end

function AtosClient:printTable(table)
   print(AtosClient:dump(table))

end

local function getHandItem(equippedItem)
   if equippedItem ~= nil then
      if equippedItem:getName() == "Geiger Teller" and
              equippedItem:getModName() == "Radiated Zones" and
              equippedItem:isActivated() then
         return true

      end
   end
end

function AtosClient:isGeigerEquipped(player)
   local attachedItems = player:getAttachedItems()
   local primaryEquippedItem = player:getPrimaryHandItem()
   local secondaryEquippedItem = player:getSecondaryHandItem()
   local currentUseDelta

   if getHandItem(primaryEquippedItem) or getHandItem(secondaryEquippedItem) then
      return true
   end


   for count = 0, attachedItems:size() - 1 do
      if attachedItems:getItemByIndex(count):getName() == "Geiger Teller"
         and attachedItems:getItemByIndex(count):isActivated()
         and attachedItems:getItemByIndex(count):getUsedDelta() > 0
      then
            return true
      end
   end
   return false
end

function AtosClient:getTime()
   print(GameTime:getInstance():getHour())
end

function test(player)
   local items = player:getWornItems()

   for count = 1, items:size() - 1 do
      print(items:getItemByIndex(count):getClothingItemName())
      if items:getItemByIndex(count):getClothingItemName() == "HazmatSuit" then
         print(tostring(items:getItemByIndex(count):isVanilla()))
         print(items:getItemByIndex(count):getModData())
      end
   end

end

function AtosClient:playerIsProtectedByClothingType(player)
   local items = player:getWornItems()
   local isSpeedFrameworkActivated = getActivatedMods():contains("SpeedFramework")

   for count = 1, items:size() - 1 do
      local clothingItem = items:getItemByIndex(count)
      local clothingItemType = clothingItem:getType()

      --print(items:getItemByIndex(count):getClothingItemName())
      if clothingItemType == "HazmatSuit" then

         if isSpeedFrameworkActivated then
            SpeedFramework.SetPlayerSpeed(player, 0.7)
         end

         if clothingItem:getHolesNumber() < 1
         and clothingItem:getCurrentCondition() > 0 then
            return "Hazmat"
         end

      elseif clothingItemType == "Hat_GasMask" then
         if AtosClient:getUsedDelta(clothingItem) > 0 then
            return "GasMask"

         end
         
      end

   end

   if isSpeedFrameworkActivated then
      SpeedFramework.SetPlayerSpeed(player, nil)
   end
   return "Nothing"

end

function AtosClient:useGasMask(player)
   local items = player:getWornItems()

   for count = 1, items:size() - 1 do
      local item = items:getItemByIndex(count)
      local itemType = item:getType()

      if itemType == "Hat_GasMask" then
         local currentUseDelta = AtosClient:getUsedDelta(item)
         local usage = 2.5
         if currentUseDelta <= 0 then
            AtosClient:setUsedDelta(item, 0)
         else
            AtosClient:setUsedDelta(item, currentUseDelta - usage)
         end
      end

   end

end

function AtosClient:dump(o)
   if type(o) == 'table' then
      local s = '{ '
      for k,v in pairs(o) do
         if type(k) ~= 'number' then k = '"'..k..'"' end
         s = s .. '['..k..'] = ' .. AtosClient:dump(v) .. ','
      end
      return s .. '} '
   else
      return tostring(o)
   end
end

function AtosClient:tableLength(T)
   local count = 0
   for k, v in pairs(T) do
      count = count + 1
   end
   return count
end
