---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Wesley.
--- DateTime: 29/07/2023 15:31
---
local AtosClient = AtosDangerZones.Client

local function doMenu(player, context, items)
    for i, v in ipairs(items) do
        local item = v;
        if not instanceof(v, "InventoryItem") then
            item = v.items[1];
        end

        if item:getType() then
            if item:getType() == "GeigerTeller" then
                context:addOption(getText("ContextMenu_measure_radiation"), item, measureRadiation, player);
            --elseif item:getType() == "Iodine" then
            --    context:addOption(getText("ContextMenu_Take_pills"), item, takeIodinePill, player);

            end
        end
    end
end

function takeIodinePill(item, player)
    local playerObj = getSpecificPlayer(player);
    ISTimedActionQueue.add(AtosTakeIodinePill:new(playerObj, item))
end

function measureRadiation(item, player)
    -- This is where the code goes for when someone clicks the option in the menu
    local playerObj = getSpecificPlayer(player);
    ISTimedActionQueue.add(AtosIsMeasureRadiationAction:new(playerObj, item))

end

-- The link to the right-click menu event
Events.OnFillInventoryObjectContextMenu.Add(doMenu);
