---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Atophite.
--- DateTime: 04/10/2022 19:23
---
---

if isServer() and not isClient() then
	return
end

local player = getPlayer()

local geigerSound = nil
--Is radiation detected by the geiger teller
local isRadiationDetected = false
local isInZone = false
local isProtected = false
local sickness = 1
local hasGeiger = false
local hasEnteredZone = false

local zones

local AtosClient = AtosDangerZones.Client
local AtosShared = AtosDangerZones.Shared

local function onGameStart()
	player = getPlayer()

	--if client is online send request to server
	if isClient() then
		print("requesting zones")
		sendClientCommand("Atos", "RequestAllZones", {
			player = player
		});
	else
		--If client is offline, manually read the file
		zones = AtosShared:readZonesFile()
	end

end

function testCommand()
	zones = AtosShared:readCorsFile()
	print(isClient())
	sendClientCommand("Atos", "RequestAllZones", {
		player = player
	});
end

local function onConnected()
	print("Connected to server")
end

local function OnGameBoot()
	print("game is booted!")
end

local function everyOneMinute()
	--If zones are empty
	--sendClientCommand only works on multiplayer
	--For some reason the sendClientCommand doesnt work on onGameStart()
	if zones == nil then
		if(isClient()) then
			sendClientCommand("Atos", "RequestAllZones", {
				player = player
			});
		else
			zones = AtosShared:readZonesFile()
		end
	else
		AtosClient:loopZones()
	end
end



function AtosClient:onClothingUpdated()

	--https://zomboid-javadoc.com/41.65/zombie/characters/ILuaGameCharacterClothing.html

	--getModID
	--Check if player equipped a geiger when clothing is updated
	--Also checks if the player already has the geiger equipped.
	if AtosClient:isGeigerEquipped(player) and not hasGeiger then
		hasGeiger = true

		if not isInZone then
			player:Say("Radiation not detected!")
		elseif isInZone then
			player:Say("Radiation detected!")
		end

	elseif not AtosClient:isGeigerEquipped(player) then
		hasGeiger = false
	end

	if AtosClient:isPlayerProtected(player) then
		isProtected = true
	else
		isProtected = false
	end
end


function AtosClient:loopZones()
	local playerX = player:getLx()
	local playerY = player:getLy()
	isInZone = false

	--Check if ATOS_player is in the zone
	--zone[1][1] is lowest x coordinate and zone[1][2] is highest.
	--Same with y coordinate
	for i, zone in ipairs(zones) do
		if(playerX > zone[1][1] and playerX < zone[1][2] and playerY > zone[2][1] and playerY < zone[2][2]) then
			isInZone = true
		end
	end

	AtosClient:validateZone()
end


function AtosClient:validateZone()

	-- Check if the player is in the radiation zone
	if isInZone then

		--Check if its the first time that the ATOS_player has entered the zone.
		--To prevent a loop
		if not hasEnteredZone then

			if hasGeiger then
				player:Say("Radiation detected!")
			end
			hasEnteredZone = true
			AtosClient:onClothingUpdated()
		end


		if isProtected then
			print("player is wearing protection")
		else
			print("player is NOT wearing protection")
			sickness = sickness * 1.2
			if(sickness >= 100) then
				print(sickness)
				player:getBodyDamage():setFoodSicknessLevel(20);
			elseif sickness >= 200 then
				player:getBodyDamage():setFoodSicknessLevel(40);
			end

		end

		--If the ATOS_player has a geiger the ATOS_player can detect the radiation
		if hasGeiger then
			isRadiationDetected = true
			AtosClient:playSound()
		else
			isRadiationDetected = false
			AtosClient:stopSound()
		end
	else
		--Check if its the first time that the player has left the zone.
		--To prevent a loop
		if hasEnteredZone then
			AtosClient:stopSound()
			--Send message to server that player left zone.
			if hasGeiger then
				player:Say("Radiation not detected!")
			end

			hasEnteredZone = false
		end
	end
end

function AtosClient:playSound()
	if geigerSound == nil then
		geigerSound = player:playSound("Geiger")

	elseif geigerSound ~= nil and not player:getEmitter():isPlaying(geigerSound) and hasGeiger == true then
		geigerSound = player:playSound("Geiger")
	end
end

function AtosClient:stopSound()
	if geigerSound ~= nil and isRadiationDetected or not hasGeiger then
		player:getEmitter():stopSoundByName("Geiger")

		geigerSound = nil
	end
end

function AtosClient:setZones(paramZones)
	zones = paramZones
end

Events.OnClothingUpdated.Add(AtosClient.onClothingUpdated)
Events.OnGameStart.Add(onGameStart)
Events.EveryOneMinute.Add(everyOneMinute)
Events.OnConnected.Add(onConnected)
Events.OnGameBoot.Add(OnGameBoot)


