---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Atophite.
--- DateTime: 04/10/2022 19:23
---
---
if isServer() and not isClient() then
    print("Im a server")
    return
end

--Listen to server commands
local function OnServerCommand(module, command, arguments)
    print("Getting server command")
    ATOS_setZones(arguments.zones)

    if module == "Atos" and command == "GetAllZones" then
        print("Getting all zones")
        print(arguments.zones)
        if arguments.zones then
            ATOS_setZones(arguments.zones)
        end
    end

end

Events.OnServerCommand.Add(OnServerCommand)