---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Wesley.
--- DateTime: 28/07/2023 13:25
---
RadiatedZones = {}
RadiatedZones.OnCreate = {}

--TODO

function RadiatedZones.OnCreate.GeigerTellerBatteryInsert(items, result, player)
    print("insert test")
    --for i=0, items:size()-1 do
    --    -- we found the battery, we change his used delta according to the battery
    --    if items:get(i):getType() == "Battery" then
    --        result:setUsedDelta(items:get(i):getUsedDelta());
    --    end
    --end
end