---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Atophite.
--- DateTime: 07/08/2023 19:45
------

require "TimedActions/ISBaseTimedAction"

AtosIsCheckGeigerAction = ISBaseTimedAction:derive("AtosIsCheckGeigerAction");
local AtosClient = AtosRadiatedZones.Client

function AtosIsCheckGeigerAction:isValid() -- Check if the action can be done
    local currentUseDelta = self.item:getUsedDelta()

    if currentUseDelta <= 0 then
        self.character:Say(getText("ContextMenu_out_of_battery"))
        return false
    end

    return true;
end

function AtosIsCheckGeigerAction:update() -- Trigger every game update when the action is perform
    self.item:setJobDelta(self:getJobDelta());
end

function AtosIsCheckGeigerAction:start() -- Trigger when the action start
    self.item:setJobType(getText("ContextMenu_check_geiger"));
    self.item:setJobDelta(0.0);
    self:setOverrideHandModels(nil, self.item);
    self:setActionAnim("MedicalCheck")
end

function AtosIsCheckGeigerAction:stop() -- Trigger if the action is cancel
    self.item:setJobDelta(0.0);
    ISBaseTimedAction.stop(self);
end

function AtosIsCheckGeigerAction:perform() -- Trigger when the action is complete
    self.item:setJobDelta(0.0);
    if AtosClient:getIsInZone() then
        self.character:Say(getText("ContextMenu_radiation_detected"))
    else
        self.character:Say(getText("ContextMenu_radiation_not_detected"))
    end

    local currentUseDelta = self.item:getUsedDelta()
    local deltaUsage = 0.01

    self.item:setUsedDelta(currentUseDelta - deltaUsage)

    local newCurrentUseDelta = self.item:getUsedDelta()

    if newCurrentUseDelta <= 0 then
        self.item:setReplaceOnUse("EmptyGeigerTeller")
    end

    ISBaseTimedAction.perform(self);
end

function AtosIsCheckGeigerAction:new(character, item) -- What to call in you code
    local o = {};
    setmetatable(o, self);
    self.__index = self;
    o.item = item
    o.character = character;
    o.maxTime = 100; -- Time take by the action
    if o.character:isTimedActionInstant() then o.maxTime = 1; end
    return o;
end