---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Wesley.
--- DateTime: 29/07/2023 15:55
---

--THIS IS CURRENTLY NOT BEING USED SINCE THE DELTA OF THE PILLS ARE NOT BEING REDUCED WHEN PILLS ARE BEING TAKEN
--BUGGED OR SOMETHING
--IODINE ARE FOOD NOW AND USED THE On_Eat FUNCTION LOOK AT AtosItems.txt

require "TimedActions/ISBaseTimedAction"

AtosTakeIodinePill = ISBaseTimedAction:derive("AtosTakeIodinePill");

local AtosClient = AtosRadiatedZones.Client

function AtosTakeIodinePill:isValid() -- Check if the action can be done
    return true;
end

function AtosTakeIodinePill:update() -- Trigger every game update when the action is perform
    self.item:setJobDelta(self:getJobDelta());
    self:setActionAnim(CharacterActionAnims.TakePills);
end

function AtosTakeIodinePill:start() -- Trigger when the action start
    self.item:setJobType(getText("ContextMenu_Take_pills"));
    self.item:setJobDelta(0.0);
    self:setOverrideHandModels(nil, self.item);
end

function AtosTakeIodinePill:stop() -- Trigger if the action is cancel
    ISBaseTimedAction.stop(self);
    self.item:setJobDelta(0.0);
end

function AtosTakeIodinePill:perform() -- Trigger when the action is complete
    self.item:getContainer():setDrawDirty(true);
    self.item:setJobDelta(0.0);
    self.character:getBodyDamage():JustTookPill(self.item);

    AtosClient:setIsProtectedByPills(true)
    AtosClient:setIsProtectedByPillsSince(GameTime:getInstance():getWorldAgeHours())
    AtosClient:setIodineMoodle(1.0)
    local rad = AtosClient:getRadiation()
    local minusRad = 25

    if rad <= 25 then
        AtosClient:setRadiation(1)
    else
        AtosClient:setRadiation(rad - 25)
    end
    self.item:setUseDelta(0.1)
    ISBaseTimedAction.perform(self);
end

function AtosTakeIodinePill:new(character, item) -- What to call in you code
    local o = {};
    setmetatable(o, self);
    self.__index = self;
    o.item = item
    o.character = character;
    o.maxTime = 200; -- Time take by the action
    o.stopOnWalk = false;
    o.stopOnRun = true;
    if o.character:isTimedActionInstant() then o.maxTime = 1; end
    return o;
end