---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Wesley.
--- DateTime: 13/07/2023 22:03
---

require "Items/ProceduralDistributions"

--ArmySurplusTools
table.insert(ProceduralDistributions.list["ArmySurplusTools"].items, "Base.HazmatSuit");
table.insert(ProceduralDistributions.list["ArmySurplusTools"].items, 5);

table.insert(ProceduralDistributions.list["ArmySurplusTools"].items, "DangerZone.GeigerTeller");
table.insert(ProceduralDistributions.list["ArmySurplusTools"].items, 5);


--ArmyStorageMedical
table.insert(ProceduralDistributions.list["ArmyStorageMedical"].items, "DangerZone.GeigerTeller");
table.insert(ProceduralDistributions.list["ArmyStorageMedical"].items, 10);
table.insert(ProceduralDistributions.list["ArmyStorageMedical"].items, "DangerZone.Iodine");
table.insert(ProceduralDistributions.list["ArmyStorageMedical"].items, 10);

--ArmyStorageElectronics
table.insert(ProceduralDistributions.list["ArmyStorageElectronics"].items, "DangerZone.GeigerTeller");
table.insert(ProceduralDistributions.list["ArmyStorageElectronics"].items, 10);

--ArmySurplusMisc
table.insert(ProceduralDistributions.list["ArmySurplusMisc"].items, "DangerZone.GeigerTeller");
table.insert(ProceduralDistributions.list["ArmySurplusMisc"].items, 1);

--DrugLabOutfit
table.insert(ProceduralDistributions.list["DrugLabOutfit"].items, "Base.HazmatSuit");
table.insert(ProceduralDistributions.list["DrugLabOutfit"].items, 25);

--DrugLabSupplies
table.insert(ProceduralDistributions.list["DrugLabSupplies"].items, "DangerZone.Iodine");
table.insert(ProceduralDistributions.list["DrugLabSupplies"].items, 5);

table.insert(ProceduralDistributions.list["CrateCarpentry"].items, "DangerZone.Iodine");
table.insert(ProceduralDistributions.list["CrateCarpentry"].items, 100);
table.insert(ProceduralDistributions.list["CrateCarpentry"].items, "Base.HazmatSuit");
table.insert(ProceduralDistributions.list["CrateCarpentry"].items, 100);

table.insert(ProceduralDistributions.list["BathroomCabinet"].items, "DangerZone.Iodine");
table.insert(ProceduralDistributions.list["BathroomCabinet"].items, 2);

table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "DangerZone.Iodine");
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 100);
table.insert(ProceduralDistributions.list["BookstoreMisc"].items, "DangerZone.Iodine");
table.insert(ProceduralDistributions.list["BookstoreMisc"].items, 100);
