name: Upload to Workshop
on: workflow_dispatch
  
  
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display output
        run: echo "${{ env.changelog }}"

      - name: Upload to Workshop
        uses: AnarkisGaming/workshop@v1
        with:
          appID: 108600
          #workshop ID
          publishedFileID: 3019024205
          path: "Contents/"
          # changelog: ${{ steps.changelog.outputs.changelog }}
        env:
          STEAM_ACCOUNT_NAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD  }}
