name: Upload to Workshop
on:
  schedule:
    # 1 AM every friday!
    - cron: "00 1 * * 5"
  workflow_dispatch: 
  
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Read changelog of commit
        id: changelog
        run: echo "changelog=$(git log --format=%B -n 1 ${{ github.sha }})" >> $GITHUB_OUTPUT

      - name: Display output
        run: echo "${{ env.changelog }}"

      - name: Upload to Workshop
        uses: AnarkisGaming/workshop@v1
        with:
          appID: 108600
          #workshop ID
          publishedFileID: 3019024205
          changelog: ${{ steps.changelog.outputs.changelog }}
        env:
          STEAM_ACCOUNT_NAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD  }}
